export const ROUTES = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  analytics: '/analytics',
  pipeline: '/pipeline',
  reports: '/reports',
  icp: '/icp',
  settings: '/settings',
  accountSettings: '/account',
  team: '/team',
  pricing: '/pricing',
  leads: '/leads',
  leadDetail: '/leads/:leadId',
  auditLog: '/audit',
  outreach: '/outreach',
  segments: '/segments',
  forgotPassword: '/forgot-password',
};

export const PAGE_ROUTE_MAP = {
  Home: ROUTES.home,
  Login: ROUTES.login,
  Dashboard: ROUTES.dashboard,
  Reports: ROUTES.reports,
  ICP: ROUTES.icp,
  Settings: ROUTES.settings,
  Pricing: ROUTES.pricing,
  LeadDetail: ROUTES.leadDetail,
  AuditLog: ROUTES.auditLog,
  Outreach: ROUTES.outreach,
  Segments: ROUTES.segments,
};
