export const ROUTES = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  analytics: '/analytics',
  pipeline: '/pipeline',
  outreach: '/outreach',
  icp: '/icp',
  settings: '/settings',
  accountSettings: '/account',
  team: '/team',
  pricing: '/pricing',
  leadDetail: '/leads/:leadId',
  auditLog: '/audit',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  billing: '/billing',
  help: '/help',
};
