export const ROUTES = {
  home: '/',
  login: '/login',
  dashboard: '/dashboard',
  analytics: '/analytics',
  pipeline: '/pipeline',
  icp: '/icp',
  outreach: '/outreach',
  segments: '/segments',
  reports: '/reports',
  settings: '/settings',
  accountSettings: '/account',
  team: '/team',
  pricing: '/pricing',
  leadDetail: '/leads/:leadId',
  auditLog: '/audit',
  help: '/help',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
};

export const PAGE_ROUTE_MAP = {
  Home: ROUTES.home,
  Login: ROUTES.login,
  Dashboard: ROUTES.dashboard,
  ICP: ROUTES.icp,
  Outreach: ROUTES.outreach,
  Segments: ROUTES.segments,
  Reports: ROUTES.reports,
  Settings: ROUTES.settings,
  Pricing: ROUTES.pricing,
  LeadDetail: ROUTES.leadDetail,
  AuditLog: ROUTES.auditLog,
  Help: ROUTES.help,
};
