export const toLeadAnalysisUpdatePayload = (result) => ({
  status: result.final_status || result.status,
  icp_score: result.icp_score,
  icp_raw_score: result.icp_raw_score,
  icp_category: result.category,
  icp_priority: result.priority,
  recommended_action: result.recommended_action,
  icp_profile_id: result.icp_profile_id,
  icp_profile_name: result.icp_profile_name,
  analysis_version: result.analysis_version,
  ai_score: result.ai_score,
  ai_confidence: result.ai_confidence,
  ai_signals: result.ai_signals,
  ai_summary: result.ai_summary,
  scoring_weights: result.scoring_weights,
  final_score: result.final_score,
  final_category: result.final_category,
  final_priority: result.final_priority,
  final_recommended_action: result.final_recommended_action,
  final_status: result.final_status,
  signals: result.signals,
  score_details: result.score_details,
  analysis_summary: result.analysis_summary,
  generated_icebreakers: result.generated_icebreakers,
  generated_icebreaker: result.generated_icebreakers?.email,
  // Only manual intent signals should persist. LLM inferred signals stay display-only
  // so they cannot be re-injected into later re-analyses.
  ...(result.discovered_internet_signals ? { internet_signals: result.discovered_internet_signals } : {}),
  last_analyzed_at: new Date().toISOString(),
});
